TGIF 102
hoodiehq/hood.ie pull request #335
Opened 2016-10-21 19:50 UTC by gr2m

2016-10-21 20:56 UTC, machikoyasuda commented on _posts/2016-10-21-sweet-break-before-break-102.md
> +Some of the things we discussed were TGIF having it’s own platform (separate from the blog), opening each issue up to multiple contributors (one contributor per section), making TGIF more accessible
`its` not `it's (It is)`

2016-10-21 20:58 UTC, machikoyasuda commented on _posts/2016-10-21-sweet-break-before-break-102.md
> +[FreeBSD stable/11 branch released](https://www.freebsd.org/releases/11.0R/announce.html) (freebsd.org)
Let's always spell out abbreviations on the first reference. This saves people a Google search (or, for me, a DuckDuckGo search) to learn something new. BSD, I just learned right now, stands for `Berkeley Software Distribution`. So something like: `FreeBSD (Berkeley Software Distribution) stable/11 branch released`

2016-10-21 20:58 UTC, machikoyasuda commented on _posts/2016-10-21-sweet-break-before-break-102.md
> +The OS that powers [many](https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/nutshell.html%23introduction-nutshell-users) successful projects on the web is born again, with security improveme
`operating system (OS)`

2016-10-21 20:58 UTC, machikoyasuda commented on _posts/2016-10-21-sweet-break-before-break-102.md
> +
Amazon Web Services (AWS)

2016-10-21 21:01 UTC, machikoyasuda commented
Thank you for crafting this newsletter!

I noticed we have a lot more links than usual. One of the great privledges of being a writer and editor is choosing the best of the best. Feel free to take any links _out_ if you don't 100% love them. 

I also noticed there are a lot of references to Google. Maybe we can choose the one or two _best_ news coming out from Google instead, and mix it up with smaller companies and groups that people may not know about. 

The other theme is to make sure to spell out all abbreviated names, titles on first reference. That's all! TGIF!!

2016-10-21 21:02 UTC, machikoyasuda requested changes
1. Spell out all abbreviations (BSD, OS for example)
2. Trim down the number of links to your favorite ones.

2016-10-22 05:46 UTC, gr2m commented
@igotpassion can you review it this weekend? No worries that it gets published late, still great content :)

2016-10-22 13:41 UTC, igotpassion commented on _posts/2016-10-21-sweet-break-before-break-102.md
> +[FreeBSD stable/11 branch released](https://www.freebsd.org/releases/11.0R/announce.html) (freebsd.org)
Great point.

2016-10-22 13:42 UTC, igotpassion approved these changes

2016-10-22 13:51 UTC, igotpassion commented
@gr2m The requests by @machikoyasuda are on point. Struggling without my comp (it finally burnt out from the water spill). I should be online on my friend's iPad for an hour before I hit the road again (traveling in Costa Rica). Let me know if I can do anything else. Thanks so much to you both for helping with this!

2016-10-25 06:41 UTC, gr2m commented
hey sorry I hope I would have time to finish this up over the weekend but didn’t :( let's make it ready for next Friday, okay? Very sorry for that

2016-10-27 22:27 UTC, gr2m commented
@igotpassion can you incorporate Machiko’s feedback? Maybe put in some more recent links that came up over the week? Sorry again that I didn’t manage to publish this last Friday :(

2016-10-31 13:41 UTC, renrutnnej commented on _posts/2016-10-21-sweet-break-before-break-102.md
> +I’m grateful to be part of this project and look forward to making TGIF one of the most anticipated newsletters in open source, intellect and fun! Now for what you may have missed over the past 2 wee
“in open source, intellect, and fun” might not translate well to ESL readers, I think you could be more concise here

2016-10-31 13:43 UTC, jennwrites commented on _posts/2016-10-21-sweet-break-before-break-102.md
> +## Events
Quite a few of the upcoming events [mentioned in the last TGIF](http://hood.ie/blog/hacktober-thumbs-high-level-dumplings-tgif-101.html) are missing here.

2016-10-31 13:45 UTC, renrutnnej commented on _posts/2016-10-21-sweet-break-before-break-102.md
> +[Github’s community guidelines](https://www.google.com/url?sa%3Dt%26rct%3Dj%26q%3D%26esrc%3Ds%26source%3Dweb%26cd%3D1%26cad%3Drja%26uact%3D8%26ved%3D0ahUKEwj5--qrv-zPAhXJjz4KHT_0CAsQFggeMAA%26url%3Dh
s/Github/GitHub

2016-11-02 20:05 UTC, igotpassion commented
Thanks for the feedback y'all and apologies for the delay. I'll update this with some newer link, incorporate changes, and have ready for this Friday 👍

2016-11-04 01:05 UTC, igotpassion approved these changes

2016-11-04 01:06 UTC, igotpassion approved these changes

2016-11-04 03:34 UTC, gr2m commented
I’ll be out tomorrow, @skeskali @renrutnnej @machikoyasuda can you please help get the TGIF out tomorrow?

2016-11-04 04:04 UTC, machikoyasuda commented
ill be out tomorrow as well!!






On Thu, Nov 3, 2016 at 8:34 PM -0700, "Gregor Martynus" <notifications@github.com> wrote:












I’ll be out tomorrow, @skeskali @renrutnnej @machikoyasuda can you please help get the TGIF out tomorrow?



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2016-11-04 08:05 UTC, skeskali commented
I think I can get it done, but I haven't published directly to the blog before. Is it just a matter of merging the request, or are there other steps?

2016-11-04 14:31 UTC, igotpassion commented
@skeskali I'm making final changes now (hopefully I'm doing it right as this is my first time using GitHub). I will update you when ready.

2016-11-07 21:27 UTC, igotpassion approved these changes

2016-11-08 18:26 UTC, gr2m commented
I’m sorry this got pushed off another week. I’m done with organizing Offline Camp and will be free this Friday, so can definitely help to get it out this time

2016-11-11 20:52 UTC, machikoyasuda approved these changes
👍🏽

2016-11-11 20:52 UTC, merged